apiVersion: apps/v1
kind: Deployment
metadata:
  name: productcatalog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: productcatalog
  template:
    metadata:
      labels:
        app: productcatalog
    spec:
      containers:
      - name: productcatalog
        image: productcatalog:v0.1
        ports:
        - containerPort: 8000
        env:
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://jaeger:4317
        - name: ConnectionStrings__ProductCatalog
          valueFrom:
            secretKeyRef:
              name: productcatalog
              key: dbconnection
        resources:
          limits:
            memory: 128Mi
            cpu: 500m
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: productcatalog
spec:
  selector:
    app: productcatalog
  ports:
  - port: 8000
    targetPort: 8000
---
apiVersion: v1
kind: Secret
metadata:
  name: productcatalog
type: Opaque
stringData:
  dbconnection: <TODO_SET_DB_CONNECTION_STRING>
